services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: fullsteak_admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fullsteak_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: