services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: fullsteak_admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fullsteak_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fullsteak_admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata: